/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SCD2_2021_Exam;

import SCD2_2021_Exam.facade.ApiFacade;
import SCD2_2021_Exam.facade.Cache;
import SCD2_2021_Exam.model.InputApi;
import SCD2_2021_Exam.model.InputApiOnline;
import SCD2_2021_Exam.model.InputDummyApi;
import SCD2_2021_Exam.model.ModelThread;
import SCD2_2021_Exam.model.OutputApi;
import SCD2_2021_Exam.model.OutputApiOnline;
import SCD2_2021_Exam.view.MainFrame;
import SCD2_2021_Exam.view.ViewThread;

public class App {

    public static void main(String[] args) {
        InputApi inputApi;
        OutputApi outputApi;
        //Creates api based on the user inputs
        if(args[0].equalsIgnoreCase("offline")){
            inputApi = new InputDummyApi();   
        }
        else{
            inputApi = new InputApiOnline();   
        }
        if(args[1].equalsIgnoreCase("offline")){
            outputApi =  new OutputApiOnline();   
        }
        else{
            outputApi = new OutputApiOnline();   
        }
        
        Cache cache = new Cache();
        ApiFacade api = new ApiFacade(inputApi,outputApi,cache);
        //First thread for the GUI/View 
        ViewThread viewThread = new ViewThread();
        viewThread.run();

        //Second thread for the Api calls and Cache(Model)
        ModelThread modelThread = new ModelThread(api, viewThread.getView());
        modelThread.run();
    }
}
